### ISSUE TITLE
not an issue but a request

### ISSUE THREAD

**Issue by KRIEZIEY** [SnowHubv2/apex-squirrelscripts-linux#1]
may u please make seer esp switchable or make another version visout it. your cheat is awesome but seer esp sometimes annoys me i tried to figure it  out how to disable it but i dont have any experirnce in editing vpks so i just broke anything

**Comment by SnowHubv2** [comment]
i can make an off an on switch

**Comment by KRIEZIEY** [comment]
if u make it work like that it will be cool !

**Comment by SnowHubv2** [comment]
done
