### ISSUE TITLE
A few small requests

### ISSUE THREAD

**Issue by iiiis310** [SnowHubv2/apex-squirrelscripts-linux#2]
Could you change the trigger button to mouse 5 or how to customize it?
And whether the trigger can be added with a delay effect to shoot sniper rifles
Thank you very much for making something so nice for us to use！

**Comment by iiiis310** [comment]
The title is wrong. It should be a request!

**Comment by Snomn123** [comment]
I'm adding an on/off button. Unfortunatly i can not really make anything to customize it right now.
