### ISSUE TITLE
Apex closing after replacing VPK files

### ISSUE THREAD

**Issue by HugoCG77** [SnowHubv2/apex-squirrelscripts-linux#3]
I replaced the VPK files and did everything using Injector.py, and when I press launch, my game shows eac launch for a second, then the whole game closes. I'm on Ubuntu 22.04

**Comment by Snomn123** [comment]
Either game updated or you used the injector wrong.

Execute the injector and type inject. Launch game. Set timer when in lobby. Timer can be 10 sec if you want it to be fast. Wait for the timer to get to 0 and tell you that its deleted some files. Then you can ready!

**Comment by HugoCG77** [comment]
Okay I tried what you said, and received this error "Files deleted and you can now play!

Traceback (most recent call last):
  File "/home/hugo/Desktop/Inject.py", line 51, in <module>
    os.remove(deletefile)
NotADirectoryError: [Errno 20] Not a directory: '/home/hugo/.steam/debian-installation/steamapps/common/Apex Legends/vpk/client_frontend.bsp.pak000_000.vpk/'". 

But then, I tried to grab the cheat files from the cheatfolder, and drag them into the vpk, and it quite literally just booted up normally? No cheat, just normal apex?

**Comment by Snomn123** [comment]
"/vpk/client_frontend.bsp.pak000_000.vpk/"
Theres a "/" at the end of "client_frontend.bsp.pak000_000.vpk". Remove that. Should be fixed after that.

**Comment by HugoCG77** [comment]
Okay, did that, injected, launched up apex, clicked, went to lobby screen and put 10 seconds, waited, it finished, completely normal apex? Still no cheat?

**Comment by Snomn123** [comment]
You have the wrong cheats in the cheat folder then.

**Comment by HugoCG77** [comment]
> You have the wrong cheats in the cheat folder then.

Do you mind adding my discord so we can discuss this without delay between responses? Just as I'd like to get this fixed asap. I do not know how I could possibly have the wrong cheats in the cheat folder, I installed the autoinjector, and in that zip file  was the cheat folder, so I extract everything out, grab the two files, put them in my vpk folder, and boom, normal apex?

**Comment by HugoCG77** [comment]
Hey man, just fixed it. Had to go back to windows, grab vpk files, and just redo everything and it works now. Thanks anyway though
